# Generated by Django 5.1.5 on 2025-02-07 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_about_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
